// <auto-generated />
using System;
using Cartorio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cartorio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250413225235_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cartorio.Data.Casamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CpfConjuge1")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfConjuge2")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfDaMaeConjuge1")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfDaMaeConjuge2")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfDoPaiConjuge1")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfDoPaiConjuge2")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataDeNascimentoConjuge1")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDeNascimentoConjuge2")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDaMaeConjuge1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDaMaeConjuge2")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDoPaiConjuge1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDoPaiConjuge2")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDoCasamento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDoRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NomeConjuge1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeConjuge2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDaMaeConjuge1")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDaMaeConjuge2")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoPaiConjuge1")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoPaiConjuge2")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Casamentos");
                });

            modelBuilder.Entity("Cartorio.Data.Nascimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CpfDaMae")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CpfDoPai")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDaMae")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDoPai")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDoRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NomeDaMae")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoPai")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoRegistrado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Nascimentos");
                });

            modelBuilder.Entity("Cartorio.Data.Obito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDaMae")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDeNascimentoDoPai")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDoObito")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataDoRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NomeDaMae")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoFalecido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeDoPai")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Obitos");
                });
#pragma warning restore 612, 618
        }
    }
}
